# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='com_count',
            field=models.IntegerField(default=0),
        ),
    ]
