# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='orientation',
        ),
    ]
