# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 19:27
from __future__ import unicode_literals

import apps.social_media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('social_media', '0002_post_com_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to=apps.social_media.models.profile_pic_path)),
                ('nickname', models.CharField(blank=True, max_length=55)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_reg.User')),
            ],
        ),
    ]
