# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 19:29
from __future__ import unicode_literals

import apps.social_media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('social_media', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to=apps.social_media.models.profile_pic_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_reg.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
