# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 19:31
from __future__ import unicode_literals

import apps.social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_auto_20180801_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='pic',
            field=models.ImageField(upload_to=apps.social_media.models.profile_pic_path),
        ),
    ]
