# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_auto_20180808_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user profile'},
        ),
    ]
