# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_auto_20180801_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='pic',
            new_name='photo',
        ),
    ]
