# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 21:20
from __future__ import unicode_literals

import apps.social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0007_auto_20180813_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar/avatar.jpg', upload_to=apps.social_media.models.avatar_upload_path),
        ),
    ]
